### ISSUE TITLE
this is for your reference , a update fast project

### ISSUE THREAD

**Issue by liufeijin** [j2doll/Qlibxlsxwriter#2]
https://github.com/jmcnamara/libxlsxwriter
it is not for qt specially , for your reference.
jeff

**Comment by liufeijin** [comment]
https://github.com/jmcnamara/libxlsxwriter/commit/8df3ce882c654416cf5e658b20017cf46da6358c#diff-20827109fa4f6c0bac299b5c9184f20f

**Comment by j2doll** [comment]
Dear liufejin:
I updated libxlsxwriter to v0.8.3.
https://github.com/j2doll/Qlibxlsxwriter/releases/tag/v0.1.1
I am updating libxlsxwriter very slowly, because of stability.
Thank you for reporting this issue. 😺
