### ISSUE TITLE
can't build in qt5.11.1  “zlib.h”: No such file or directory

### ISSUE THREAD

**Issue by liufeijin** [j2doll/Qlibxlsxwriter#3]
get a lot of warring   “zlib.h”: No such file or directory

But QT5.11.1 has the zlib.h in  C:\Qt\Qt5.11.1\5.11.1\msvc2017_64\include\QtZlib

**Comment by j2doll** [comment]
:one: You should install zlib development library. https://zlib.net
I recommend to use zlib for NutGet Manager on Visual Studio.
See https://github.com/j2doll/Qlibxlsxwriter/blob/master/TestEnv.md.
In most cases, it will be fine.

:two: If you installed zlib, you may ignore that warning. 
You may customize your own code to following way.

```qmake
Qlibxlsxwriter.pri

win32-msvc* {
# HEADERS += zlib.h
 HEADERS += YourOwnZlibPath/zlib.h
}
```
