### ISSUE TITLE
for zlib.h , QT5 has included it , add it in your pro file

### ISSUE THREAD

**Issue by liufeijin** [j2doll/Qlibxlsxwriter#4]
If you install with qt5 scr  , only add this in your project file  pro
INCLUDEPATH += $$[QT_INSTALL_HEADERS]/QtZlib

**Comment by j2doll** [comment]
Dear @liufeijin
- You can use it, if the zlib-devel version of the development tool is the same as the zlib version of Qt.
   - However, if the two versions are different, there may be problems in compiling or linking. And if possible, consider developing an update to zlib-devel.
- Of course, you can modify Qlibxlsxwriter.pri for various environments.
   - I have added your recommendations to the Qlibxlsxwriter.pri file. (as a comment)
- I recommend you to use the zlib-devel headers and libraries.
