### ISSUE TITLE
Add libxlsxwriter topic to the project metadata

### ISSUE THREAD

**Issue by jmcnamara** [j2doll/Qlibxlsxwriter#6]
Hi,

Good work on this library and for making it easy to use libxlsxwriter with Qt.

Could you add libxlsxwriter as a "topic" metadata to your project so that users can find wrappers in different languages.

Topic/Metadata are shown at the top of the project: https://github.com/jmcnamara/libxlsxwriter

Other examples: https://github.com/search?q=topic%3Alibxlsxwriter&type=Repositories

Thanks,

John

**Comment by j2doll** [comment]
Dear @jmcnamara 

I added a libxlsxwriter topic to this project.

It is an honor for me to add a topic.

Thank you for providing a very good project. 😃
